const express = require("express");
const AdminRouter = express.Router();
const { Adminlogin, refreshAdminAccessToken, createCategory, adminlogout, getAllCategory, getcategoryById, updateCategory, createSubCategory, getAllSubCategory, getSubcategoryById, updateProfile, updateSubCategory, getProfileById } = require("../controllers/AdminController");
const { BannerController, getBannerController, deleteBannerController, EditBannerController, updateBanner } = require("../controllers/BannerController");
const { adminauthenticate } = require("../middleware/adminauth");
const uploadSingleImage = require('../utils/uploadSingleImage');
const uploadMiddleware = require('../middleware/uploadMiddleware');
AdminRouter.post("/admin-login", Adminlogin);
AdminRouter.post("/create-category", adminauthenticate, createCategory);
AdminRouter.get("/get-all-category", adminauthenticate, getAllCategory);
AdminRouter.get("/get-category/:id", adminauthenticate, getcategoryById);
AdminRouter.put("/update-category/:id", adminauthenticate, updateCategory);
AdminRouter.post("/create-subcategory", adminauthenticate, createSubCategory);
AdminRouter.get("/get-all-subcategory", adminauthenticate, getAllSubCategory);
AdminRouter.get("/get-subcategory/:id", adminauthenticate, getSubcategoryById);
AdminRouter.put("/update-subcategory/:id", adminauthenticate, updateSubCategory);
AdminRouter.post("/refresh-admin-access-token", refreshAdminAccessToken);
AdminRouter.get("/get-profile", adminauthenticate, getProfileById);
AdminRouter.put("/update-profile", adminauthenticate, updateProfile);
AdminRouter.post("/admin-logout", adminlogout);
const allowedTypess = [".jpg", ".jpeg", ".png", ".webp"];
const maxSizes = 2 * 1024 * 1024;
const uploadBannerFolder = "uploads/banner";
const uploadBanner = uploadSingleImage(allowedTypess, maxSizes, uploadBannerFolder, "photo");
AdminRouter.post("/create-banner", uploadMiddleware(uploadBanner), adminauthenticate, BannerController);
AdminRouter.put("/update-banner/:id", uploadMiddleware(uploadBanner), adminauthenticate, updateBanner);
AdminRouter.get("/get-banner", adminauthenticate, getBannerController);
AdminRouter.get("/get-banner/:id", adminauthenticate, EditBannerController);
AdminRouter.delete("/delete-banner/:id", adminauthenticate, deleteBannerController);
module.exports = AdminRouter;
