const express = require("express");
const AdminRouter = express.Router();
const { Adminlogin, refreshAdminAccessToken, createCategory, adminlogout, getAllCategory, getcategoryById, updateCategory, createSubCategory, getAllSubCategory, getSubcategoryById, updateSubCategory } = require("../controllers/AdminController");
const { adminauthenticate } = require("../middleware/adminauth");
AdminRouter.post("/admin-login", Adminlogin);
AdminRouter.post("/create-category", adminauthenticate, createCategory);
AdminRouter.get("/get-all-category", adminauthenticate, getAllCategory);
AdminRouter.get("/get-category/:id", adminauthenticate, getcategoryById);
AdminRouter.put("/update-category/:id", adminauthenticate, updateCategory);
AdminRouter.post("/create-subcategory", adminauthenticate, createSubCategory);
AdminRouter.get("/get-all-subcategory", adminauthenticate, getAllSubCategory);
AdminRouter.get("/get-subcategory/:id", adminauthenticate, getSubcategoryById);
AdminRouter.put("/update-subcategory/:id", adminauthenticate, updateSubCategory);
AdminRouter.post("/refresh-admin-access-token", refreshAdminAccessToken);
AdminRouter.post("/admin-logout", adminlogout);
module.exports = AdminRouter;
